In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [ ]:
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [ ]:
tensor_input = tf.convert_to_tensor(inputs)
tensor_targets=tf.convert_to_tensor(targets)
print(tensor_input)

tf.Tensor(
[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]], shape=(5, 3), dtype=float32)


In [ ]:
tensor_input=torch.tensor(inputs)
tensor_targets=torch.tensor(targets)
print(tensor_input)
print(tensor_targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [9]:
from torch.utils.data import TensorDataset, DataLoader