In [ ]:
import numpy as np
import torch
import torch.nn as nn

In [22]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')


In [23]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [24]:
from torch.utils.data import TensorDataset, DataLoader
ds = TensorDataset(inputs, targets)
for inputs, targets in ds:
    print('{}:{}'.format(inputs, targets))


tensor([73., 67., 43.]):tensor([56.])
tensor([91., 88., 64.]):tensor([81.])
tensor([ 87., 134.,  58.]):tensor([119.])
tensor([102.,  43.,  37.]):tensor([22.])
tensor([69., 96., 70.]):tensor([103.])


In [25]:
dl = DataLoader(ds, batch_size=2)
for inputs, targets in dl:
    print('{}:{}'.format(inputs, targets))    

tensor([[73., 67., 43.],
        [91., 88., 64.]]):tensor([[56.],
        [81.]])
tensor([[ 87., 134.,  58.],
        [102.,  43.,  37.]]):tensor([[119.],
        [ 22.]])
tensor([[69., 96., 70.]]):tensor([[103.]])
